config/routes.rb
Rails.application.routes.draw do
  resources :fees
  resources :vehicles
  resources :scales
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
end

app/models/scale.rb
class Scale < ApplicationRecord
  has_many :vehicles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :fees
  has_many :vehicles
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
  belongs_to :scale
  has_many :fees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
  before_action :set_fee, only: [:show, :edit, :update, :destroy]

  # GET /fees
  # GET /fees.json
  def index
    @fees = Fee.all
  end

  # GET /fees/1
  # GET /fees/1.json
  def show
  end

  # GET /fees/new
  def new
    @fee = Fee.new
  end

  # GET /fees/1/edit
  def edit
  end

  # POST /fees
  # POST /fees.json
  def create
    @fee = Fee.new(fee_params)

    respond_to do |format|
      if @fee.save
        format.html { redirect_to @fee, notice: 'Fee was successfully created.' }
        format.json { render :show, status: :created, location: @fee }
      else
        format.html { render :new }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fees/1
  # PATCH/PUT /fees/1.json
  def update
    respond_to do |format|
      if @fee.update(fee_params)
        format.html { redirect_to @fee, notice: 'Fee was successfully updated.' }
        format.json { render :show, status: :ok, location: @fee }
      else
        format.html { render :edit }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fees/1
  # DELETE /fees/1.json
  def destroy
    @fee.destroy
    respond_to do |format|
      format.html { redirect_to fees_url, notice: 'Fee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fee
      @fee = Fee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fee_params
      params.require(:fee).permit(:km, :vehicle_id, :start_travel, :arrival_travel, :start_adress, :arrival_adress, :description)
    end
end

app/controllers/scales_controller.rb
class ScalesController < ApplicationController
  before_action :set_scale, only: [:show, :edit, :update, :destroy]

  # GET /scales
  # GET /scales.json
  def index
    @scales = Scale.all
  end

  # GET /scales/1
  # GET /scales/1.json
  def show
  end

  # GET /scales/new
  def new
    @scale = Scale.new
  end

  # GET /scales/1/edit
  def edit
  end

  # POST /scales
  # POST /scales.json
  def create
    @scale = Scale.new(scale_params)

    respond_to do |format|
      if @scale.save
        format.html { redirect_to @scale, notice: 'Scale was successfully created.' }
        format.json { render :show, status: :created, location: @scale }
      else
        format.html { render :new }
        format.json { render json: @scale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scales/1
  # PATCH/PUT /scales/1.json
  def update
    respond_to do |format|
      if @scale.update(scale_params)
        format.html { redirect_to @scale, notice: 'Scale was successfully updated.' }
        format.json { render :show, status: :ok, location: @scale }
      else
        format.html { render :edit }
        format.json { render json: @scale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scales/1
  # DELETE /scales/1.json
  def destroy
    @scale.destroy
    respond_to do |format|
      format.html { redirect_to scales_url, notice: 'Scale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scale
      @scale = Scale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scale_params
      params.require(:scale).permit(:vehicle_type, :coeff, :horsepower)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:user_id, :scale_id, :vehicle_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/scales_helper.rb
module ScalesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/fees/_form.html.erb
<%= form_with(model: fee, local: true) do |form| %>
  <% if fee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fee.errors.count, "error") %> prohibited this fee from being saved:</h2>

      <ul>
      <% fee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :km %>
    <%= form.number_field :km, id: :fee_km %>
  </div>

  <div class="field">
    <%= form.label :vehicle_id %>
    <%= form.text_field :vehicle_id, id: :fee_vehicle_id %>
  </div>

  <div class="field">
    <%= form.label :start_travel %>
    <%= form.datetime_select :start_travel, id: :fee_start_travel %>
  </div>

  <div class="field">
    <%= form.label :arrival_travel %>
    <%= form.datetime_select :arrival_travel, id: :fee_arrival_travel %>
  </div>

  <div class="field">
    <%= form.label :start_adress %>
    <%= form.text_field :start_adress, id: :fee_start_adress %>
  </div>

  <div class="field">
    <%= form.label :arrival_adress %>
    <%= form.text_field :arrival_adress, id: :fee_arrival_adress %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :fee_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fees/edit.html.erb
<h1>Editing Fee</h1>

<%= render 'form', fee: @fee %>

<%= link_to 'Show', @fee %> |
<%= link_to 'Back', fees_path %>

app/views/fees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fees</h1>

<table>
  <thead>
    <tr>
      <th>Km</th>
      <th>Vehicle</th>
      <th>Start travel</th>
      <th>Arrival travel</th>
      <th>Start adress</th>
      <th>Arrival adress</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fees.each do |fee| %>
      <tr>
        <td><%= fee.km %></td>
        <td><%= fee.vehicle %></td>
        <td><%= fee.start_travel %></td>
        <td><%= fee.arrival_travel %></td>
        <td><%= fee.start_adress %></td>
        <td><%= fee.arrival_adress %></td>
        <td><%= fee.description %></td>
        <td><%= link_to 'Show', fee %></td>
        <td><%= link_to 'Edit', edit_fee_path(fee) %></td>
        <td><%= link_to 'Destroy', fee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fee', new_fee_path %>

app/views/fees/new.html.erb
<h1>New Fee</h1>

<%= render 'form', fee: @fee %>

<%= link_to 'Back', fees_path %>

app/views/fees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Km:</strong>
  <%= @fee.km %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @fee.vehicle %>
</p>

<p>
  <strong>Start travel:</strong>
  <%= @fee.start_travel %>
</p>

<p>
  <strong>Arrival travel:</strong>
  <%= @fee.arrival_travel %>
</p>

<p>
  <strong>Start adress:</strong>
  <%= @fee.start_adress %>
</p>

<p>
  <strong>Arrival adress:</strong>
  <%= @fee.arrival_adress %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fee.description %>
</p>

<%= link_to 'Edit', edit_fee_path(@fee) %> |
<%= link_to 'Back', fees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appkm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scales/_form.html.erb
<%= form_with(model: scale, local: true) do |form| %>
  <% if scale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scale.errors.count, "error") %> prohibited this scale from being saved:</h2>

      <ul>
      <% scale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vehicle_type %>
    <%= form.text_field :vehicle_type, id: :scale_vehicle_type %>
  </div>

  <div class="field">
    <%= form.label :coeff %>
    <%= form.number_field :coeff, id: :scale_coeff %>
  </div>

  <div class="field">
    <%= form.label :horsepower %>
    <%= form.number_field :horsepower, id: :scale_horsepower %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scales/edit.html.erb
<h1>Editing Scale</h1>

<%= render 'form', scale: @scale %>

<%= link_to 'Show', @scale %> |
<%= link_to 'Back', scales_path %>

app/views/scales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scales</h1>

<table>
  <thead>
    <tr>
      <th>Vehicle type</th>
      <th>Coeff</th>
      <th>Horsepower</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scales.each do |scale| %>
      <tr>
        <td><%= scale.vehicle_type %></td>
        <td><%= scale.coeff %></td>
        <td><%= scale.horsepower %></td>
        <td><%= link_to 'Show', scale %></td>
        <td><%= link_to 'Edit', edit_scale_path(scale) %></td>
        <td><%= link_to 'Destroy', scale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scale', new_scale_path %>

app/views/scales/new.html.erb
<h1>New Scale</h1>

<%= render 'form', scale: @scale %>

<%= link_to 'Back', scales_path %>

app/views/scales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vehicle type:</strong>
  <%= @scale.vehicle_type %>
</p>

<p>
  <strong>Coeff:</strong>
  <%= @scale.coeff %>
</p>

<p>
  <strong>Horsepower:</strong>
  <%= @scale.horsepower %>
</p>

<%= link_to 'Edit', edit_scale_path(@scale) %> |
<%= link_to 'Back', scales_path %>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :vehicle_user_id %>
  </div>

  <div class="field">
    <%= form.label :scale_id %>
    <%= form.text_field :scale_id, id: :vehicle_scale_id %>
  </div>

  <div class="field">
    <%= form.label :vehicle_name %>
    <%= form.text_field :vehicle_name, id: :vehicle_vehicle_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Scale</th>
      <th>Vehicle name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.user %></td>
        <td><%= vehicle.scale %></td>
        <td><%= vehicle.vehicle_name %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @vehicle.user %>
</p>

<p>
  <strong>Scale:</strong>
  <%= @vehicle.scale %>
</p>

<p>
  <strong>Vehicle name:</strong>
  <%= @vehicle.vehicle_name %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>